### PR TITLE
translate class

### PR DESCRIPTION
**Pull request by lizakochel**
added text translation class and test

### CODE REVIEW

**Review by iguehi-akhimien — COMMENTED** [review]
I think you explicitly change the button name to "Translate to Russian" or include some drop down menu if you will hope translate to other languages. 
If possible, could you translate to more languages like French, Spanish, Arabic? For those languages, you could include a functionality to translate to English.

**Review by PrishaPatel24 — CHANGES_REQUESTED** [review]
- Coding style is good; variables are named descriptively and some comments provided
- One success test is included, but you can add some failure cases
- The code only uses the View component of clean architecture, so consider breaking it up into more classes (ex. InputData, OutputData)
- Should add Javadocs to follow coding style and make purposes of classes/methods more clear

**Review by stickycorner — CHANGES_REQUESTED** [review]
I really like your usage of the input and output data, but just note that there's a couple of facets of clean architecture that you're missing from your use case:
- Presenter
- Interactor
- Controller
- Input/Output Boundary Interfaces

@PrishaPatel24's changes following CA are already merged into main so feel free to check out her work  if you want a reference to set up the CA for the use case.

**Review by iguehi-akhimien — APPROVED** [review]
- It is good that you included a test class for the use case. 
- I think either one of us may need to rename the inputData and outputData class for our use cases.
- Also, don't forget to include Javadoc comments for each class and methods (where necessary).

**Review by iguehi-akhimien — CHANGES_REQUESTED** [review]
Everything you did was easy to follow. I was wondering, what is Translator?
Apart from that, I would like to suggest some changes:

- In the MainNoteApplication, you pass in a parameter of type OutputBoundary not Presenter into the Interactor (because of Clean Architecture).
- Also, you should pass in ViewModel into the Presenter, instead of View (because of clean architecture).
- I was wondering if you could probably rename "NoteTranslation" to "TranslationFactory", since you are interacting with InputData and OutputData, and you need the translated object. This will show that you used and understood Design Patterns. Then, the Interactor will call the factory. 
- I am not sure, but should the test class be for the Interactor?

**Review by PrishaPatel24 — COMMENTED** [review]
- I agree with the first thing Igee said about OutputBoundary, it will probably be a slight refactoring
- You should definitely have an Interactor test; it's one of the requirements for your use case
- I don't think you need an explicit ViewModel because your use case is not really visual
- Functionality seems good

**Comment by lizakochel** [comment]
*In the most recent commit, I meant to say "changed to TranslationInteractorTest"

**Comment by lizakochel** [comment]
Looks like main has some issues that need to be resolved-- when I tried to run the newest version of main, it didn't compile

**Review by PrishaPatel24 — APPROVED** [review]

**Review by iguehi-akhimien — APPROVED** [review]

**Review by stickycorner — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
